<?php


namespace Bytes\EnumSerializerBundle\Enums;


use JetBrains\PhpStorm\ArrayShape;
use JetBrains\PhpStorm\Deprecated;
use Spatie\Enum\Enum as ParentEnum;

/**
 * Class Enum
 * @package Bytes\EnumSerializerBundle\Enums
 */
abstract class Enum extends ParentEnum
{
    use EnumTrait;

    /** @psalm-readonly */
    #[Deprecated(reason: 'since 1.6.0, there is no label')]
    protected string $label;

    /**
     * @param string|int $value
     *
     * @return static
     */
    #[Deprecated(reason: 'since 1.3.1, use from() instead', replacement: '%class%::from(%parameter0%)')]
    public static function make($value): Enum
    {
        return static::from($value);
    }

    /**
     * @return string[]
     */
    #[Deprecated(reason: 'since 1.6.0, use "cases()" instead.', replacement: '%class%::cases()')]
    public static function getLabels(): array
    {
        trigger_deprecation('mrgoodbytes8667/enum-serializer-bundle', '1.6.0', 'Using "%s" is deprecated, use "%s()" instead.', __METHOD__, 'cases');
        return static::toLabels();
    }

    #[Deprecated(reason: 'since 1.6.0, use "cases()" instead.', replacement: '%class%::cases()')]
    public static function toLabels(): array
    {
        trigger_deprecation('mrgoodbytes8667/enum-serializer-bundle', '1.6.0', 'Using "%s" is deprecated, use "%s()" instead.', __METHOD__, 'cases');
        return parent::toLabels(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string[]|int[]
     */
    #[Deprecated(reason: 'since 1.6.0, use "cases()" instead.', replacement: '%class%::cases()')]
    public static function getValues(): array
    {
        trigger_deprecation('mrgoodbytes8667/enum-serializer-bundle', '1.6.0', 'Using "%s" is deprecated, use "%s()" instead.', __METHOD__, 'cases');
        return static::toValues();
    }

    #[Deprecated(reason: 'since 1.6.0, use "cases()" instead.', replacement: '%class%::cases()')]
    public static function toValues(): array
    {
        trigger_deprecation('mrgoodbytes8667/enum-serializer-bundle', '1.6.0', 'Using "%s" is deprecated, use "%s()" instead.', __METHOD__, 'cases');
        return parent::toValues(); // TODO: Change the autogenerated stub
    }

    #[Deprecated(reason: 'since 1.6.0, use "cases()" instead.', replacement: '%class%::cases()')]
    public static function toArray(): array
    {
        trigger_deprecation('mrgoodbytes8667/enum-serializer-bundle', '1.6.0', 'Using "%s" is deprecated, use "%s()" instead.', __METHOD__, 'cases');
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|int|string
     */
    #[ArrayShape(['label' => "string", 'value' => "int|string"])]
    public function jsonSerialize()
    {
        return [
            'label' => $this->label,
            'value' => $this->value
        ];
    }
}