name: Code Coverage

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 1.*
      - 2.*
      - 3.*
      - 4.*
      - 5.*
      - 6.*
      - 7.*
      - 8.*
      - 9.*

jobs:
  coverage:
    uses: mrgoodbytes8667/workflows/.github/workflows/code-coverage.yml@php8.1-8.3
    secrets: inherit
    with:
      phpUnitVersion: 9.6
      coverageType: xdebug